name: portfolio_dbt
version: "1.0.0"
config-version: 2

profile: portfolio_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  portfolio_dbt:
    nba:
      staging:
        +materialized: view
        +schema: nba_dbt
      intermediate:
        +materialized: view
        +schema: nba_dbt
      marts:
        +materialized: table
        +schema: nba_dbt
    toronto_parking:
      staging:
        +materialized: view
        +schema: toronto_parking_dbt_staging
      intermediate:
        +materialized: view
        +schema: toronto_parking_dbt_intermediate
      marts:
        facts:
          +materialized: incremental
          +schema: toronto_parking_dbt_marts
        dims:
          +materialized: table
          +schema: toronto_parking_dbt_marts
        reporting:
          +materialized: table
          +schema: toronto_parking_dbt_marts

seeds:
  portfolio_dbt:
    +schema: seeds

snapshots:
  portfolio_dbt:
    +schema: snapshots

