name: toronto_parking_dbt
version: "1.0.0"
config-version: 2

profile: toronto_parking_dbt

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  toronto_parking_dbt:
    staging:
      +materialized: view
      +schema: toronto_parking_dbt_staging
    intermediate:
      +materialized: view
      +schema: toronto_parking_dbt_intermediate
    marts:
      facts:
        +materialized: incremental
        +schema: toronto_parking_dbt_marts
      dims:
        +materialized: table
        +schema: toronto_parking_dbt_marts
      reporting:
        +materialized: table
        +schema: toronto_parking_dbt_marts

seeds:
  toronto_parking_dbt:
    +schema: seeds
